version: "3"

services:
  app:
    image: node
    working_dir: /home/node/app
    depends_on:
      - db
    links:
      - db
    command: "npm run start:debug"
    ports:
      - 3001:3001
      - 9229:9229
    tty: true
    volumes:
      - .:/home/node/app
    networks:
      vpcbr:
        ipv4_address: 172.44.9.3

  db:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - 3306:3306    
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=exclusible
    networks:
      vpcbr:
        ipv4_address: 172.44.9.4

networks:
  vpcbr:
    ipam:
      config:
        - subnet: 172.44.9.0/24
